### ISSUE TITLE
Suggestion: allow to destroy an item on empty if the charges are depleted by a spell

### ISSUE THREAD

**Issue by InnilToo** [ElfFriend-DnD/foundryvtt-items-with-spells-5e#2]
Use case: Spell Scrolls

Can't use spell scrolls more than once so it would be nice if after you cast the spell and consume the one charge on the spell scroll the item would get deleted. This already works if you click on the item itself but not if the charges are reduced to 0 by some other item consuming its charges.

_(But that may need to be a core FVTT/DnD5e feature?)_

**Comment by akrigline** [comment]
Spell scrolls in particular are already handled by the core system, drag and drop a spell into the actor's inventory instead of spell book tab and it will create one.

The destroy on empty behavior for items with charges that are consumed by other items is a shortcoming of the core system. I don't think I'll be changing that with this module though.

**Comment by InnilToo** [comment]
Oh I had no idea that you can already make spell scrolls...
That solves my problem then, thank you and sorry for the bother.
